# Generated by Django 5.2.9 on 2025-12-19 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='collections/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('composition', models.CharField(blank=True, help_text='e.g., 100% Cotton, 60% Cotton 40% Polyester', max_length=200)),
                ('care_instructions', models.TextField(blank=True)),
                ('is_natural', models.BooleanField(default=True)),
                ('is_stretch', models.BooleanField(default=False)),
                ('weight', models.CharField(blank=True, help_text='e.g., Lightweight, Medium, Heavy', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('LEATHER', 'Leather'), ('METAL', 'Metal'), ('WOOD', 'Wood'), ('PLASTIC', 'Plastic'), ('FABRIC', 'Fabric'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category_type', models.CharField(choices=[('CLOTHING', 'Clothing'), ('ACCESSORIES', 'Accessories'), ('FOOTWEAR', 'Footwear'), ('OTHER', 'Other')], default='CLOTHING', help_text='Determines which product attributes are relevant', max_length=20)),
                ('requires_fabric', models.BooleanField(default=True, help_text='Does this category require fabric info?')),
                ('requires_fit', models.BooleanField(default=True, help_text='Does this category require fit info?')),
                ('requires_size_chart', models.BooleanField(default=True, help_text='Does this category require size chart?')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('fabric_composition', models.CharField(blank=True, help_text='Detailed fabric composition (overrides fabric.composition if needed)', max_length=200)),
                ('fit', models.CharField(blank=True, choices=[('SLIM', 'Slim Fit'), ('REGULAR', 'Regular Fit'), ('LOOSE', 'Loose Fit'), ('OVERSIZED', 'Oversized'), ('TAILORED', 'Tailored Fit'), ('ATHLETIC', 'Athletic Fit'), ('RELAXED', 'Relaxed Fit'), ('SKINNY', 'Skinny Fit'), ('STRAIGHT', 'Straight Fit'), ('TAPERED', 'Tapered Fit'), ('BOXY', 'Boxy Fit'), ('BOOTCUT', 'Bootcut'), ('JOGGER', 'Jogger Fit'), ('CLASSIC', 'Classic Fit'), ('MODERN', 'Modern Fit'), ('CUSTOM', 'Custom Fit'), ('OTHER', 'Other')], default='REGULAR', help_text='How the garment fits', max_length=20, null=True)),
                ('size_chart_image', models.ImageField(blank=True, help_text='Upload size chart as image', null=True, upload_to='size_charts/')),
                ('size_chart_description', models.TextField(blank=True, help_text='Or describe size chart details as text')),
                ('measurements', models.JSONField(blank=True, default=dict, help_text='Product measurements in JSON format. Example:\n        {\n            "guide": "Body measurements in inches",\n            "size_m": {"chest": "40", "waist": "34", "length": "28"},\n            "size_l": {"chest": "42", "waist": "36", "length": "29"},\n            "model_info": "Model is 6\'0" wearing size L"\n        }')),
                ('style_code', models.CharField(blank=True, db_index=True, help_text='Manufacturer/style code (e.g., MCT001-BLK)', max_length=50)),
                ('collar_type', models.CharField(blank=True, choices=[('CREW_NECK', 'Crew Neck'), ('V_NECK', 'V-Neck'), ('POLO', 'Polo Collar'), ('HENLEY', 'Henley'), ('TURTLENECK', 'Turtleneck'), ('MOCK_NECK', 'Mock Neck'), ('HOODED', 'Hooded'), ('BAND_COLLAR', 'Band Collar'), ('MANDARIN', 'Mandarin Collar'), ('SPREAD', 'Spread Collar'), ('BUTTON_DOWN', 'Button Down Collar'), ('CAMP', 'Camp Collar'), ('NOTCH', 'Notch Lapel'), ('SHAWL', 'Shawl Collar'), ('NO_COLLAR', 'No Collar'), ('OTHER', 'Other')], help_text='e.g., Crew Neck, V-Neck, Polo', max_length=50)),
                ('sleeve_type', models.CharField(blank=True, choices=[('SHORT', 'Short Sleeve'), ('LONG', 'Long Sleeve'), ('THREE_QUARTER', '3/4 Sleeve'), ('SLEEVELESS', 'Sleeveless'), ('RAGLAN', 'Raglan Sleeve'), ('DOLMAN', 'Dolman Sleeve'), ('BATWING', 'Batwing Sleeve'), ('BELL', 'Bell Sleeve'), ('PUFFED', 'Puffed Sleeve'), ('CUFFED', 'Cuffed Sleeve'), ('CAP', 'Cap Sleeve'), ('KIMONO', 'Kimono Sleeve'), ('OTHER', 'Other')], help_text='e.g., Short Sleeve, Long Sleeve', max_length=50)),
                ('pattern', models.CharField(blank=True, choices=[('SOLID', 'Solid'), ('STRIPED', 'Striped'), ('CHECKED', 'Checked/Plaid'), ('PRINTED', 'Printed'), ('DOTTED', 'Dotted/Polka Dot'), ('CAMOUFLAGE', 'Camouflage'), ('GRAPHIC', 'Graphic Print'), ('TIE_DYE', 'Tie-Dye'), ('EMBROIDERED', 'Embroidered'), ('JACQUARD', 'Jacquard'), ('TEXTURED', 'Textured'), ('FLORAL', 'Floral'), ('ANIMAL', 'Animal Print'), ('GEOMETRIC', 'Geometric'), ('ABSTRACT', 'Abstract'), ('OTHER', 'Other')], help_text='e.g., Solid, Striped, Checkered', max_length=100)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='For accessories: dimensions in JSON format')),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='catalog.collection')),
                ('fabric', models.ForeignKey(blank=True, help_text='Primary fabric/material of the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.fabric')),
                ('material', models.ForeignKey(blank=True, help_text='Material for accessories (leather, metal, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_products', to='catalog.material')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx'), models.Index(fields=['sku'], name='catalog_pro_sku_187601_idx')],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
