# Generated by Django 5.2.9 on 2025-12-16 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('composition', models.CharField(blank=True, help_text='e.g., 100% Cotton, 60% Cotton 40% Polyester', max_length=200)),
                ('care_instructions', models.TextField(blank=True)),
                ('is_natural', models.BooleanField(default=True)),
                ('is_stretch', models.BooleanField(default=False)),
                ('weight', models.CharField(blank=True, help_text='e.g., Lightweight, Medium, Heavy', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('LEATHER', 'Leather'), ('METAL', 'Metal'), ('WOOD', 'Wood'), ('PLASTIC', 'Plastic'), ('FABRIC', 'Fabric'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('CLOTHING', 'Clothing'), ('ACCESSORIES', 'Accessories'), ('FOOTWEAR', 'Footwear'), ('OTHER', 'Other')], default='CLOTHING', help_text='Determines which product attributes are relevant', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_fabric',
            field=models.BooleanField(default=True, help_text='Does this category require fabric info?'),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_fit',
            field=models.BooleanField(default=True, help_text='Does this category require fit info?'),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_size_chart',
            field=models.BooleanField(default=True, help_text='Does this category require size chart?'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='product',
            name='collar_type',
            field=models.CharField(blank=True, choices=[('CREW_NECK', 'Crew Neck'), ('V_NECK', 'V-Neck'), ('POLO', 'Polo Collar'), ('HENLEY', 'Henley'), ('TURTLENECK', 'Turtleneck'), ('MOCK_NECK', 'Mock Neck'), ('HOODED', 'Hooded'), ('BAND_COLLAR', 'Band Collar'), ('MANDARIN', 'Mandarin Collar'), ('SPREAD', 'Spread Collar'), ('BUTTON_DOWN', 'Button Down Collar'), ('CAMP', 'Camp Collar'), ('NOTCH', 'Notch Lapel'), ('SHAWL', 'Shawl Collar'), ('NO_COLLAR', 'No Collar'), ('OTHER', 'Other')], help_text='e.g., Crew Neck, V-Neck, Polo', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, help_text='For accessories: dimensions in JSON format'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition',
            field=models.CharField(blank=True, help_text='Detailed fabric composition (overrides fabric.composition if needed)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, choices=[('SLIM', 'Slim Fit'), ('REGULAR', 'Regular Fit'), ('LOOSE', 'Loose Fit'), ('OVERSIZED', 'Oversized'), ('TAILORED', 'Tailored Fit'), ('ATHLETIC', 'Athletic Fit'), ('RELAXED', 'Relaxed Fit'), ('SKINNY', 'Skinny Fit'), ('STRAIGHT', 'Straight Fit'), ('TAPERED', 'Tapered Fit'), ('BOXY', 'Boxy Fit'), ('BOOTCUT', 'Bootcut'), ('JOGGER', 'Jogger Fit'), ('CLASSIC', 'Classic Fit'), ('MODERN', 'Modern Fit'), ('CUSTOM', 'Custom Fit'), ('OTHER', 'Other')], default='REGULAR', help_text='How the garment fits', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, help_text='Product measurements in JSON format. Example:\n        {\n            "guide": "Body measurements in inches",\n            "size_m": {"chest": "40", "waist": "34", "length": "28"},\n            "size_l": {"chest": "42", "waist": "36", "length": "29"},\n            "model_info": "Model is 6\'0" wearing size L"\n        }'),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, choices=[('SOLID', 'Solid'), ('STRIPED', 'Striped'), ('CHECKED', 'Checked/Plaid'), ('PRINTED', 'Printed'), ('DOTTED', 'Dotted/Polka Dot'), ('CAMOUFLAGE', 'Camouflage'), ('GRAPHIC', 'Graphic Print'), ('TIE_DYE', 'Tie-Dye'), ('EMBROIDERED', 'Embroidered'), ('JACQUARD', 'Jacquard'), ('TEXTURED', 'Textured'), ('FLORAL', 'Floral'), ('ANIMAL', 'Animal Print'), ('GEOMETRIC', 'Geometric'), ('ABSTRACT', 'Abstract'), ('OTHER', 'Other')], help_text='e.g., Solid, Striped, Checkered', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart_description',
            field=models.TextField(blank=True, help_text='Or describe size chart details as text'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart_image',
            field=models.ImageField(blank=True, help_text='Upload size chart as image', null=True, upload_to='size_charts/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve_type',
            field=models.CharField(blank=True, choices=[('SHORT', 'Short Sleeve'), ('LONG', 'Long Sleeve'), ('THREE_QUARTER', '3/4 Sleeve'), ('SLEEVELESS', 'Sleeveless'), ('RAGLAN', 'Raglan Sleeve'), ('DOLMAN', 'Dolman Sleeve'), ('BATWING', 'Batwing Sleeve'), ('BELL', 'Bell Sleeve'), ('PUFFED', 'Puffed Sleeve'), ('CUFFED', 'Cuffed Sleeve'), ('CAP', 'Cap Sleeve'), ('KIMONO', 'Kimono Sleeve'), ('OTHER', 'Other')], help_text='e.g., Short Sleeve, Long Sleeve', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='style_code',
            field=models.CharField(blank=True, db_index=True, help_text='Manufacturer/style code (e.g., MCT001-BLK)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(blank=True, help_text='Primary fabric/material of the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material for accessories (leather, metal, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_products', to='catalog.material'),
        ),
    ]
