# Generated by Django 5.2.9 on 2025-12-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Show this product in Best Sellers section on Home page'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this product in Featured section on Home page'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text='Master switch to control home page visibility'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/original/'),
        ),
    ]
