# Generated by Django 5.2.9 on 2025-12-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Only required for main (root) categories', null=True, upload_to='categories/'),
        ),
    ]
