# Generated by Django 5.2.9 on 2025-12-29 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='uniq_active_style_name')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ForeignKey(blank=True, help_text='Client style like OXFORD SHIRT / TWILL SHIRT etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.style'),
        ),
    ]
