# Generated by Django 5.2.9 on 2025-12-17 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('concept_design_manager', 'Concept & Design Manager'), ('tech_designer', 'Tech Designer'), ('procurement_merchant', 'Procurement Merchant'), ('ecom_operations_manager', 'E-Com Operations Manager'), ('ecom_uploader', 'E-Com Product Uploader'), ('logistics_manager', 'Logistics & Supply Chain Manager'), ('warehouse_staff', 'Warehouse Staff'), ('accounts_manager', 'Accounts Manager'), ('customer', 'Customer')], help_text='Business role type (ecom_uploader, manager, etc.)', max_length=50)),
                ('name', models.CharField(help_text='Example: E-Com Uploader (Shirts)', max_length=120)),
                ('category', models.ForeignKey(blank=True, help_text='NULL = all categories (manager). Set = restricted to one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_roles', to='catalog.category')),
                ('permissions', models.ManyToManyField(blank=True, related_name='admin_roles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'ordering': ['role', 'category', 'name'],
                'unique_together': {('role', 'category')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(help_text='Employee ID from HR/Company system.', max_length=50, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can log into Django admin.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role_group', models.ForeignKey(blank=True, help_text='Select a role-group to auto-attach permissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.adminrole')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
