# Generated by Django 5.2.9 on 2026-01-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID from HR/Company system.', max_length=50, null=True, unique=True),
        ),
    ]
