# Generated by Django 5.2.9 on 2025-12-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalinstance',
            name='entity_id',
            field=models.UUIDField(),
        ),
    ]
