# Generated by Django 5.2.9 on 2026-01-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_engine', '0002_alter_approvalaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalaction',
            name='action',
            field=models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('comment', 'Comment'), ('resubmit', 'Resubmit')], max_length=20),
        ),
    ]
